version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scooby_api
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_SERVER: ${POSTGRES_SERVER:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-scooby_db}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - scooby_network
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: scooby_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-scooby_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scooby_network

volumes:
  postgres_data:

networks:
  scooby_network:
    driver: bridge 