"""add_image_urls

Revision ID: 2f5f47de9b04
Revises: b4a2b0648ef4
Create Date: 2024-04-13 12:34:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5f47de9b04'
down_revision = 'b4a2b0648ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('image_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'image_urls')
    # ### end Alembic commands ### 